/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
export {}
declare global {
  const BaseIcon: typeof import('../shared/component')['BaseIcon']
  const BaseLoading: typeof import('../shared/component')['BaseLoading']
  const BaseText: typeof import('../shared/component')['BaseText']
  const Helmet: typeof import('react-helmet-async')['Helmet']
  const HelmetProvider: typeof import('react-helmet-async')['HelmetProvider']
  const a: typeof import('from')['a']
  const c: typeof import('from')['c']
  const classNames: typeof import('classnames')['default']
  const component: typeof import('../shared/component')['default']
  const createRef: typeof import('react')['createRef']
  const e: typeof import('from')['e']
  const forwardRef: typeof import('react')['forwardRef']
  const lazy: typeof import('react')['lazy']
  const memo: typeof import('react')['memo']
  const r: typeof import('from')['r']
  const startTransition: typeof import('react')['startTransition']
  const t: typeof import('from')['t']
  const useCallback: typeof import('react')['useCallback']
  const useContext: typeof import('react')['useContext']
  const useDebugValue: typeof import('react')['useDebugValue']
  const useDeferredValue: typeof import('react')['useDeferredValue']
  const useEffect: typeof import('react')['useEffect']
  const useId: typeof import('react')['useId']
  const useImperativeHandle: typeof import('react')['useImperativeHandle']
  const useInsertionEffect: typeof import('react')['useInsertionEffect']
  const useLayoutEffect: typeof import('react')['useLayoutEffect']
  const useMemo: typeof import('react')['useMemo']
  const useReducer: typeof import('react')['useReducer']
  const useRef: typeof import('react')['useRef']
  const useState: typeof import('react')['useState']
  const useSyncExternalStore: typeof import('react')['useSyncExternalStore']
  const useTransition: typeof import('react')['useTransition']
}
// for type re-export
declare global {
  // @ts-ignore
  export type { CSSProperties, ReactNode, FunctionComponent } from 'react'
}
